/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.sensorsimulator;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int about001a=0x7f020000;
        public static final int advanced=0x7f020001;
        public static final int alert001a=0x7f020002;
        public static final int alert_add001a=0x7f020003;
        public static final int alert_application001a=0x7f020004;
        public static final int alert_delete001a=0x7f020005;
        public static final int background001a=0x7f020006;
        public static final int background_orange=0x7f020007;
        public static final int border_gray_01b=0x7f020008;
        public static final int border_orange_01b=0x7f020009;
        public static final int contact_share001a=0x7f02000a;
        public static final int directory=0x7f02000b;
        public static final int folder=0x7f02000c;
        public static final int icon=0x7f02000d;
        public static final int image001a=0x7f02000e;
        public static final int location_center001a=0x7f02000f;
        public static final int locations_add001a=0x7f020010;
        public static final int locations_add_alert001a=0x7f020011;
        public static final int locations_application001a=0x7f020012;
        public static final int locations_delete001a=0x7f020013;
        public static final int locations_favorite_application001a=0x7f020014;
        public static final int locations_small001a=0x7f020015;
        public static final int locations_view001a=0x7f020016;
        public static final int lock001a=0x7f020017;
        public static final int magnoliabg2=0x7f020018;
        public static final int magnoliabg3=0x7f020019;
        public static final int mediaplayer_application001a=0x7f02001a;
        public static final int mobile001a=0x7f02001b;
        public static final int mobile001a_32=0x7f02001c;
        public static final int mobile_shake001a=0x7f02001d;
        public static final int mobile_shake001a_32=0x7f02001e;
        public static final int mobile_shake_application001a=0x7f02001f;
        public static final int music001a=0x7f020020;
        public static final int new_doc=0x7f020021;
        public static final int open_icon=0x7f020022;
        public static final int openintents002a=0x7f020023;
        public static final int openintents002a_32=0x7f020024;
        public static final int openintents_icon=0x7f020025;
        public static final int question001a=0x7f020026;
        public static final int realdevice01a=0x7f020027;
        public static final int restore001a=0x7f020028;
        public static final int sdcard002a=0x7f020029;
        public static final int sdcard002a_32=0x7f02002a;
        public static final int search=0x7f02002b;
        public static final int sensorsimulator01b=0x7f02002c;
        public static final int settings001a=0x7f02002d;
        public static final int settings001a_32=0x7f02002e;
        public static final int shiny_button_pause=0x7f02002f;
        public static final int shiny_button_pause_1=0x7f020030;
        public static final int shiny_button_pause_selected=0x7f020031;
        public static final int shiny_button_play=0x7f020032;
        public static final int shiny_button_play_1=0x7f020033;
        public static final int shiny_button_play_selected=0x7f020034;
        public static final int shiny_button_record001c=0x7f020035;
        public static final int shiny_button_record001c_selected=0x7f020036;
        public static final int shiny_button_record_1=0x7f020037;
        public static final int shiny_button_recording001c=0x7f020038;
        public static final int shiny_button_recording_1=0x7f020039;
        public static final int shiny_button_repeat_a=0x7f02003a;
        public static final int shiny_button_repeat_a_1=0x7f02003b;
        public static final int shiny_button_repeat_a_selected=0x7f02003c;
        public static final int shiny_button_repeat_ab=0x7f02003d;
        public static final int shiny_button_repeat_ab_1=0x7f02003e;
        public static final int shiny_button_repeat_ab_selected=0x7f02003f;
        public static final int shiny_button_repeat_b=0x7f020040;
        public static final int shiny_button_repeat_b_1=0x7f020041;
        public static final int shiny_button_repeat_b_selected=0x7f020042;
        public static final int shiny_button_reset=0x7f020043;
        public static final int shiny_button_reset_1=0x7f020044;
        public static final int shiny_button_reset_selected=0x7f020045;
        public static final int shiny_button_stop=0x7f020046;
        public static final int shiny_button_stop_1=0x7f020047;
        public static final int shiny_button_stop_selected=0x7f020048;
        public static final int shiny_panel_background_001a=0x7f020049;
        public static final int shiny_slider_background001c=0x7f02004a;
        public static final int shiny_slider_knob001a=0x7f02004b;
        public static final int shoppinglist001b=0x7f02004c;
        public static final int shoppinglist01d=0x7f02004d;
        public static final int shoppinglist_application001a=0x7f02004e;
        public static final int shoppinglistcleanup001b=0x7f02004f;
        public static final int shoppinglistdelete001b=0x7f020050;
        public static final int shoppinglistnew001b=0x7f020051;
        public static final int shoppinglistrename001b=0x7f020052;
        public static final int shoppinglisttheme001a=0x7f020053;
        public static final int subtitle=0x7f020054;
        public static final int tag001a=0x7f020055;
        public static final int tag_add001a=0x7f020056;
        public static final int tag_blue=0x7f020057;
        public static final int tag_delete001a=0x7f020058;
        public static final int tagging_application001a=0x7f020059;
        public static final int tagging_magnolia_application001a=0x7f02005a;
        public static final int tagging_magnolia_settings=0x7f02005b;
        public static final int tagging_packages001a=0x7f02005c;
        public static final int theme_android=0x7f02005d;
        public static final int title_background_transparency_01c=0x7f02005e;
        public static final int trash=0x7f02005f;
        public static final int video001a=0x7f020060;
        public static final int video002a=0x7f020061;
        public static final int view_001a=0x7f020062;
        public static final int window=0x7f020063;
    }
    public static final class id {
        public static final int buttonconnect=0x7f050005;
        public static final int buttondisconnect=0x7f050006;
        public static final int content1=0x7f050001;
        public static final int content2=0x7f050004;
        public static final int datatype=0x7f050008;
        public static final int enabled=0x7f05000a;
        public static final int imagetype=0x7f050007;
        public static final int ipaddress=0x7f050002;
        public static final int sensordata=0x7f05000b;
        public static final int sensordatalist=0x7f050009;
        public static final int socket=0x7f050003;
        public static final int tabhost=0x7f050000;
        public static final int updaterate=0x7f05000c;
    }
    public static final class layout {
        public static final int sensorsimulator=0x7f030000;
        public static final int sensorsimulator_row=0x7f030001;
    }
    public static final class string {
        public static final int IP_address=0x7f040005;
        public static final int ask_update_interval=0x7f04000d;
        public static final int auto_update=0x7f04000a;
        public static final int connect=0x7f040002;
        public static final int connect_to_sensorsimulator=0x7f04000f;
        public static final int disabled=0x7f04000b;
        public static final int disconnect=0x7f040004;
        public static final int enable_sensors=0x7f040009;
        public static final int new_item=0x7f040014;
        public static final int real_device_data=0x7f040007;
        public static final int sensor_simulator_data=0x7f040008;
        /**   Sensor Simulator 
         */
        public static final int sensorsimulator=0x7f040000;
        public static final int sensorsimulator_settings=0x7f04000e;
        public static final int sensorsimulator_settings_description=0x7f040010;
        public static final int sensorsimulator_testing_description=0x7f040011;
        public static final int set_update_interval=0x7f04000c;
        public static final int settings=0x7f040001;
        public static final int socket=0x7f040006;
        public static final int testing=0x7f040003;
        public static final int update_rate=0x7f040012;
        public static final int update_rate_seconds=0x7f040013;
    }
}
